---
apiVersion: v1
kind: Namespace
metadata:
  name: maybank-project

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assestment-config
  namespace: maybank-project
data:
  assestment.conf: |
    key=value

---
apiVersion: v1
kind: Secret
metadata:
  name: assestment-secret
  namespace: maybank-project
type: Opaque
data:
  username: aXphaWRkaW4=
  password: aGFzc2Fu

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: maybank-project
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-12345678

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: maybank-project
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assestment-deployment
  namespace: maybank-project
spec:
  replicas: 9
  selector:
    matchLabels:
      app: assestment-app
  template:
    metadata:
      labels:
        app: assestment-app
    spec:
      containers:
      - name: assestment-container
        image: busybox
        command: ["sleep", "3600"]
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: assestment-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: assestment-secret
              key: password
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: efs-volume
          mountPath: /mnt/data
      volumes:
      - name: config-volume
        configMap:
          name: assestment-config
      - name: efs-volume
        persistentVolumeClaim:
          claimName: efs-claim

---
apiVersion: v1
kind: Service
metadata:
  name: assestment-service
  namespace: maybank-project
spec:
  selector:
    app: assestment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assestment-ingress
  namespace: maybank-project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: assestment-service
            port:
              number: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: assestment-hpa
  namespace: maybank-project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assestment-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
